### ISSUE TITLE
Ability to add class on selected accordion items to have open on page load

### ISSUE THREAD

**Issue by hmartens** [DavideTriso/aria-accordion#14]
I love your script, thank you so much for contributing this!

I would like to be able to add a class to a button element for that specific ones to be open on page load.

Is that currently available?

Thank you.

**Comment by DavideTriso** [comment]
Hello, at the moment what you need is not available (you can only have the first accordion open on page load), but I think this could be actually a good feature for the plugin. I will work on that as soon as possible.

**Comment by DavideTriso** [comment]
Feature added in v2.0.0.
Just add the `expandedClass` to an accordion to have it open on page load:

```html
 <article class="accordion-group__accordion accordion-group__accordion_expanded"> 
```

**Comment by hmartens** [comment]
Thank you so much @DavideTriso , I really appreciate your help and quick response! You're a legend!
